-- 춘대학
-- SELECT
-- 1
SELECT DEPARTMENT_NAME AS "학과 명", CATEGORY AS "계열"
FROM TB_DEPARTMENT;

-- 2 CAPACITY, DEPARTMENT_NAME
SELECT DEPARTMENT_NAME || '의 정원은' || ' ' || CAPACITY || '명 입니다.' AS "학과별 정원"
FROM TB_DEPARTMENT;

-- 3
SELECT STUDENT_NAME
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (D.DEPARTMENT_NO = S.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과' AND ABSENCE_YN = 'Y';

-- 4
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NAME DESC;

-- 5
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

-- 6
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- 7
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 8
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT
ORDER BY CATEGORY ASC;

-- 10
--SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
--FROM TB_STUDENT
--WHERE TO_CHAR(ENTRANCE_DATE,

---------------------------------------------------- 함수 ---------------------------------------
-- 1

























--------------------------------------------------------- DDL -------------------------------------
-- 1
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);

SELECT * FROM TB_CATEGORY;
INSERT INTO TB_CATEGORY
VALUES('ㅁㄴ', DEFAULT);

-- 2
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

-- 3
ALTER TABLE TB_CATEGORY ADD PRIMARY KEY(NAME);

-- 4
ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;

-- 5
ALTER TABLE TB_CATEGORY MODIFY(NAME VARCHAR2(20));
ALTER TABLE TB_CLASS_TYPE MODIFY(NO VARCHAR2(10));
ALTER TABLE TB_CLASS_TYPE MODIFY(NAME VARCHAR2(20));

-- 6
ALTER TABLE TB_CATEGORY RENAME COLUMN NAME to CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO to CLASS_TYPE_NO;

-- 7
ALTER TABLE TB_CATEGORY RENAME COLUMN CATEGORY_NAME to PK_CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN CLASS_TYPE_NO to PK_CLASS_TYPE_NO;

-- 8
INSERT INTO TB_CATEGORY VALUES ('공학','Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES ('의학','Y');
INSERT INTO TB_CATEGORY VALUES ('예체능','Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회','Y');
COMMIT;

-- 9
ALTER TABLE TB_DEPARTMENT ADD FOREIGN KEY(CATEGORY) REFERENCES TB_CATEGORY(PK_CATEGORY_NAME);

-- 10
CREATE OR REPLACE VIEW VW_학생일반정보
AS SELECT STUDENT_NAME, DEPARTMENT_NAME, PROFESSOR_NAME
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN TB_PROFESSOR P ON (COACH_PROFESSOR_NO = PROFESSOR_NO);
SELECT * FROM VW_학생일반정보;

-- 11
CREATE OR REPLACE VIEW VW_지도면담
AS SELECT STUDENT_NAME, DEPARTMENT_NAME, PROFESSOR_NAME
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN TB_PROFESSOR P ON (COACH_PROFESSOR_NO = PROFESSOR_NO);

-- 12
CREATE OR REPLACE VIEW VW_학과별학생수
AS SELECT DEPARTMENT_NAME, COUNT(STUDENT_NO)
FROM TB_DEPARTMENT D
JOIN TB_STUDENT S ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
GROUP BY DEPARTMENT_NAME;
    