-- 1. 23년에 산 사람들 이름과 각각의 상품과 개수를 출력
SELECT C.NAME, B.PCODE, B.QUANTITY,
EXTRACT(YEAR FROM B.BUY_DATE)
FROM TBL_BUY B
JOIN TBL_CUSTOM C ON (B.CUSTOMID = C.CUSTOM_ID)
WHERE EXTRACT(YEAR FROM B.BUY_DATE) = 2023;

-- 2. 고객들이 산 상품을 확인할 수 있도록 VIEW로 출력(뷰 이름 VW_TBL, 구입날짜 출력은 0000년, 00월, 00일)                                           
CREATE OR REPLACE VIEW VW_TBL
AS SELECT C.NAME AS "이름", P.PNAME AS "상품이름", B.QUANTITY AS "개수", TO_CHAR(B.BUY_DATE, 'YYYY"년" MM"월" DD"일"') AS "구입날짜"
FROM TBL_CUSTOM C
JOIN TBL_BUY B ON (B.CUSTOMID = C.CUSTOM_ID)
JOIN TBL_PRODUCT P ON (P.PCODE = B.PCODE)
ORDER BY "이름", "개수";

SELECT * FROM VW_TBL;
