-- 3
SELECT BOOK_NO, BOOK_NM
FROM TB_BOOK
WHERE LENGTH(BOOK_NM) >= 25;

-- 4
SELECT WRITER_NM, OFFICE_TELNO, HOME_TELNO, MOBILE_NO
FROM (
    SELECT WRITER_NM, OFFICE_TELNO, HOME_TELNO, MOBILE_NO
    FROM TB_WRITER
    WHERE MOBILE_NO LIKE '019%' AND WRITER_NM LIKE '김%'
    ORDER BY WRITER_NM
)
WHERE ROWNUM = 1;

-- 5 *
SELECT COUNT(COMPOSE_TYPE) AS "작가(명)"
FROM TB_BOOK_AUTHOR
WHERE COMPOSE_TYPE = '옮김';

-- 6 *
SELECT COMPOSE_TYPE, COUNT(*)
FROM TB_BOOK_AUTHOR
WHERE COMPOSE_TYPE IS NOT NULL
HAVING COUNT(*) >=300
GROUP BY COMPOSE_TYPE;


-- 7
SELECT BOOK_NM, ISSUE_DATE, PUBLISHER_NM
FROM (
    SELECT BOOK_NM, ISSUE_DATE, PUBLISHER_NM
    FROM TB_BOOK
    ORDER BY ISSUE_DATE DESC
)
WHERE ROWNUM = 1;

-- 8
SELECT * 
FROM (
    SELECT W.WRITER_NM , COUNT(B.BOOK_NO) 
    FROM TB_BOOK_AUTHOR BA
    JOIN TB_WRITER W ON W.WRITER_NO = BA.WRITER_NO
    JOIN TB_BOOK B ON B.BOOK_NO = BA.BOOK_NO
    GROUP BY W.WRITER_NM
    ORDER BY COUNT(B.BOOK_NO) DESC
)
WHERE ROWNUM <= 3;
-- 9
UPDATE TB_WRITER W
SET W.REGIST_DATE = (
    SELECT MIN(B.ISSUE_DATE)
    FROM TB_BOOK_AUTHOR BA
    JOIN TB_BOOK B ON BA.BOOK_NO = B.BOOK_NO
    WHERE BA.WRITER_NO = W.WRITER_NO
)
WHERE W.REGIST_DATE IS NULL;

SELECT WRITER_NM, REGIST_DATE FROM TB_WRITER;

COMMIT;



-- 10
CREATE TABLE TB_BOOK_TRANSLATOR(
    BOOK_NO VARCHAR2(10),
    WRITER_NO VARCHAR2(10), 
    CONSTRAINT PK_BOOK_TRANSLATOR PRIMARY KEY(BOOK_NO, WRITER_NO),
    CONSTRAINT FK_BOOK_TRANSLATOR_01 FOREIGN KEY (BOOK_NO) REFERENCES TB_BOOK(BOOK_NO),
    CONSTRAINT FK_BOOK_TRANSLATOR_02 FOREIGN KEY (WRITER_NO) REFERENCES TB_WRITER(WRITER_NO),
    TRANS_LANG VARCHAR2(60)
);

-- 11
INSERT ALL
INTO TB_BOOK_TRANSLATOR VALUES(BOOK_NO, WRITER_NO, TRANS_LANG)
    SELECT BOOK_NO, WRITER_NO, COMPOSE_TYPE AS "TRANS_LANG"
    FROM TB_BOOK_AUTHOR
    WHERE COMPOSE_TYPE IN ('옮기', '역주', '편역', '공역') AND COMPOSE_TYPE IS NULL;
    
SELECT * FROM TB_BOOK_TRANSLATOR;

-- 12
SELECT BOOK_NM, WRITER_NM, ISSUE_DATE
FROM TB_BOOK B
JOIN TB_BOOK_AUTHOR BA ON (B.BOOK_NO = BA.BOOK_NO)
JOIN TB_WRITER W ON (BA.WRITER_NO = W.WRITER_NO)
WHERE TO_CHAR(ISSUE_DATE, 'YYYY') = '2007';

-- 13
CREATE VIEW VW_BOOK_TRANSLATOR
AS SELECT BOOK_NM, WRITER_NM, ISSUE_DATE
FROM TB_BOOK B
JOIN TB_BOOK_AUTHOR BA ON (B.BOOK_NO = BA.BOOK_NO)
JOIN TB_WRITER W ON (BA.WRITER_NO = W.WRITER_NO)
WHERE TO_CHAR(ISSUE_DATE, 'YYYY') = '2007'
WITH READ ONLY;

-- 14
INSERT INTO TB_PUBLISHER
VALUES('춘 출판사', '02-6710-3737', DEFAULT);


-- 15
SELECT WRITER_NM, COUNT(*)
FROM TB_WRITER
WHERE WRITER_NM IS NOT NULL
GROUP BY WRITER_NM
HAVING COUNT(*) > 1;

-- 16
UPDATE TB_BOOK_AUTHOR
    SET COMPOSE_TYPE = '지음'
    WHERE COMPOSE_TYPE IS NULL;
SELECT COMPOSE_TYPE FROM TB_BOOK_AUTHOR;

-- 17 02
SELECT WRITER_NM, OFFICE_TELNO
FROM TB_WRITER
WHERE OFFICE_TELNO 